version: '3.7'
services:

  prachi-am-home:
    image: prachi-am-home
    volumes:
      - ./UI/HomeApp:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    command: "ng serve --port 4200 --host 0.0.0.0 --public-host=\"http://0.0.0.0:4200\" --disable-host-check"

  prachi-am-publisher:
    image: prachi-am-publisher
    volumes:
      - ./UI/PublisherApp:/app
      - /app/node_modules
    ports:
      - "4201:4201"
    command: "ng serve --port 4201 --host 0.0.0.0 --public-host=\"http://0.0.0.0:4201\" --disable-host-check"

  prachi-am-subscriber:
    image: prachi-am-subscriber
    volumes:
      - ./UI/SubscriberApp:/app
      - /app/node_modules
    ports:
      - "4202:4202"
    command: "ng serve --port 4202 --host 0.0.0.0 --public-host=\"http://0.0.0.0:4202\" --disable-host-check"

  prachi-am-nginx:
    image: prachi-am-nginx
    ports:
      - "80:80"
    volumes:
      - ./UI/nginx/etc/nginx.conf:/etc/nginx/nginx.conf
      - ./UI/nginx/etc/conf.d/nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - ./UI/nginx/logs:/var/log/nginx
    command: ["nginx", "-g", "daemon off;"]