version: '3.7'
services:

  prachi-am-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=am-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@email.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin:/root/.pgadmin

  prachi-am-api:
    image: prachi-am-api
    ports:
      - "8080:80"
      - "8081:443"
    depends_on:
      - prachi-am-db

  prachi-am-home:
    image: prachi-am-home
    volumes:
      - ./UI/HomeApp:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    command: "ng serve --port 4200 --host 0.0.0.0 --public-host=\"http://0.0.0.0:4200\" --disable-host-check"
    depends_on:
      - prachi-am-api

  prachi-am-publisher:
    image: prachi-am-publisher
    volumes:
      - ./UI/PublisherApp:/app
      - /app/node_modules
    ports:
      - "4201:4201"
    command: "ng serve --port 4201 --host 0.0.0.0 --public-host=\"http://0.0.0.0:4201\" --base-href /PublisherApp/ --disable-host-check"
    depends_on:
      - prachi-am-home

  prachi-am-subscriber:
    image: prachi-am-subscriber
    volumes:
      - ./UI/SubscriberApp:/app
      - /app/node_modules
    ports:
      - "4202:4202"
    command: "ng serve --port 4202 --host 0.0.0.0 --public-host=\"http://0.0.0.0:4202\" --base-href /SubscriberApp/ --disable-host-check"
    depends_on:
      - prachi-am-home

  prachi-am-nginx:
    image: prachi-am-nginx
    ports:
      - "80:80"
    volumes:
      - ./UI/nginx/etc/nginx.conf:/etc/nginx/nginx.conf
      - ./UI/nginx/etc/conf.d/nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - ./UI/nginx/logs:/var/log/nginx
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - prachi-am-publisher
      - prachi-am-subscriber