version: '3.7'
services:
  docker-prachi-service:
    image: prachi-docker
    volumes:
      - ./HomeApp:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    command: "ng serve --port 4200 --host 0.0.0.0 --public-host=\"http://0.0.0.0:4200\" --disable-host-check"
  docker-nginx:
    image: docker-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/etc/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc/conf.d/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    command: ["nginx", "-g", "daemon off;"]
    links:
      - prachi-docker