FROM node:alpine as SubscriberApp

RUN apk update && apk add --no-cache make git

WORKDIR /app

COPY SubscriberApp/package*.json  /app/

RUN npm install @angular/cli@6.0.8 -g \
    && npm ci

COPY SubscriberApp /app

EXPOSE 4201