FROM node:16-alpine as SubscriberApp

RUN apk update && apk add --no-cache make git

WORKDIR /app

COPY SubscriberApp/package*.json  /app/

RUN npm install @angular/cli@13.1.2 -g \
    && npm ci

COPY SubscriberApp /app

EXPOSE 4201