FROM node:16-alpine as PublisherApp

RUN apk update && apk add --no-cache make git

WORKDIR /app

COPY PublisherApp/package*.json  /app/

RUN npm install @angular/cli@13.1.2 -g \
    && npm ci

COPY PublisherApp /app

EXPOSE 4201