FROM node:16-alpine as HomeApp

RUN apk update && apk add --no-cache make git

WORKDIR /app

COPY HomeApp/package*.json  /app/

RUN npm install @angular/cli@13.1.2 -g \
    && npm ci

COPY HomeApp /app

EXPOSE 4200